spring:
  datasource:
    url: jdbc:postgresql://localhost/sarafan
    username: postgres
    password: 121art121
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 8062706185-014usago478fts0cc2sl09q8rcn2ccdi.apps.googleusercontent.com
            client-secret: kDSyk-XeeiK93BwLvySQjRtd
            scope: openid,email,profile

  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema: classpath:session_tables.sql
server:
  port: 9000


